repos:
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.3.2
    hooks:
    -   id: style-files
        args: [--scope=spaces, --reindention=specify_reindention('#')]
    -   id: parsable-R
